name: Release

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nicoverbruggen/fntbld-oci:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build fonts
        run: python3 build.py

      - name: Validate generated fonts with ots-sanitize
        run: |
          for font in out/ttf/*.ttf out/kf/*.ttf; do
            echo "Validating ${font}"
            ots-sanitize "${font}"
          done

      - name: Create zip files
        if: startsWith(gitea.ref, 'refs/tags/')
        run: |
          cd out/ttf && zip -j /tmp/Sourcerer.zip *.ttf
          cd $GITHUB_WORKSPACE/out/kf  && zip -j /tmp/KF_Sourcerer.zip *.ttf

      - name: Create release
        if: startsWith(gitea.ref, 'refs/tags/')
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          draft: false
          tag_name: ${{ gitea.ref_name }}
          name: Sourcerer (${{ gitea.ref_name }})
          body: |
            > [!TIP]
            > **If you are using a Kobo device and reading books purchased from the Kobo Store or reading `kepub` files converted via Calibre**, you should download KF_Sourcerer.zip, which has fonts slightly altered for optimal kerning for the `kepub` renderer.

            ### Learn more

            Sourcerer is part of the `ebook-fonts` collection. For more information about those fonts, screenshots and how to install them, please consult the README. The FAQ also includes an entry on how to enable ligatures on Kobo devices, which is highly recommended.
          files: |
            /tmp/Sourcerer.zip
            /tmp/KF_Sourcerer.zip
